export const currencyByRupee: Currency[] = [
  { name: 'US DOLLAR', value: 0.012, flag: '🇺🇸', symbol: '$' },
  { name: 'EURO', value: 0.011, flag: '🇪🇺', symbol: '€' },
  { name: 'POUND STERLING', value: 0.009, flag: '🇬🇧', symbol: '£' },
  { name: 'JAPANESE YEN', value: 1.76, flag: '🇯🇵', symbol: '¥' },
  { name: 'CHINESE YUAN', value: 0.086, flag: '🇨🇳', symbol: '¥' },
  { name: 'SOUTH KOREAN WON', value: 16.8, flag: '🇰🇷', symbol: '₩' },
  { name: 'CANADIAN DOLLAR', value: 0.017, flag: '🇨🇦', symbol: 'C$' },
  { name: 'AUSTRALIAN DOLLAR', value: 0.019, flag: '🇦🇺', symbol: 'A$' },
  { name: 'SWISS FRANC', value: 0.011, flag: '🇨🇭', symbol: 'CHF' },
  { name: 'SINGAPORE DOLLAR', value: 0.016, flag: '🇸🇬', symbol: 'S$' },
  { name: 'UAE DIRHAM', value: 0.044, flag: '🇦🇪', symbol: 'د.إ' },
  { name: 'SAUDI RIYAL', value: 0.046, flag: '🇸🇦', symbol: '﷼' },
  { name: 'KUWAITI DINAR', value: 0.0037, flag: '🇰🇼', symbol: 'KD' },
  { name: 'QATARI RIYAL', value: 0.044, flag: '🇶🇦', symbol: 'QR' },
  { name: 'BAHRAINI DINAR', value: 0.0045, flag: '🇧🇭', symbol: 'BD' },
  { name: 'OMANI RIAL', value: 0.0046, flag: '🇴🇲', symbol: '﷼' },
  { name: 'NEW ZEALAND DOLLAR', value: 0.021, flag: '🇳🇿', symbol: 'NZ$' },
  { name: 'HONG KONG DOLLAR', value: 0.094, flag: '🇭🇰', symbol: 'HK$' },
  { name: 'THAI BAHT', value: 0.40, flag: '🇹🇭', symbol: '฿' },
  { name: 'MALAYSIAN RINGGIT', value: 0.053, flag: '🇲🇾', symbol: 'RM' },
  { name: 'INDONESIAN RUPIAH', value: 198, flag: '🇮🇩', symbol: 'Rp' },
  { name: 'PHILIPPINE PESO', value: 0.69, flag: '🇵🇭', symbol: '₱' },
  { name: 'VIETNAMESE DONG', value: 311, flag: '🇻🇳', symbol: '₫' },
  { name: 'TAIWAN DOLLAR', value: 0.39, flag: '🇹🇼', symbol: 'NT$' },
  { name: 'TURKISH LIRA', value: 0.48, flag: '🇹🇷', symbol: '₺' },
  { name: 'RUSSIAN RUBLE', value: 0.95, flag: '🇷🇺', symbol: '₽' },
  { name: 'UKRAINIAN HRYVNIA', value: 0.52, flag: '🇺🇦', symbol: '₴' },
  { name: 'POLISH ZLOTY', value: 0.046, flag: '🇵🇱', symbol: 'zł' },
  { name: 'CZECH KORUNA', value: 0.28, flag: '🇨🇿', symbol: 'Kč' },
  { name: 'HUNGARIAN FORINT', value: 4.3, flag: '🇭🇺', symbol: 'Ft' },
  { name: 'SWEDISH KRONA', value: 0.13, flag: '🇸🇪', symbol: 'kr' },
  { name: 'NORWEGIAN KRONE', value: 0.14, flag: '🇳🇴', symbol: 'kr' },
  { name: 'DANISH KRONE', value: 0.082, flag: '🇩🇰', symbol: 'kr' },
  { name: 'BRAZILIAN REAL', value: 0.068, flag: '🇧🇷', symbol: 'R$' },
  { name: 'ARGENTINE PESO', value: 15.2, flag: '🇦🇷', symbol: '$' },
  { name: 'MEXICAN PESO', value: 0.23, flag: '🇲🇽', symbol: '$' },
  { name: 'CHILEAN PESO', value: 11.3, flag: '🇨🇱', symbol: '$' },
  { name: 'COLOMBIAN PESO', value: 50.0, flag: '🇨🇴', symbol: '$' },
  { name: 'SOUTH AFRICAN RAND', value: 0.22, flag: '🇿🇦', symbol: 'R' },
  { name: 'EGYPTIAN POUND', value: 0.60, flag: '🇪🇬', symbol: 'E£' },
  { name: 'NIGERIAN NAIRA', value: 19.0, flag: '🇳🇬', symbol: '₦' },
  { name: 'KENYAN SHILLING', value: 1.55, flag: '🇰🇪', symbol: 'KSh' },
  { name: 'PAKISTANI RUPEE', value: 3.4, flag: '🇵🇰', symbol: '₨' },
  { name: 'BANGLADESHI TAKA', value: 1.45, flag: '🇧🇩', symbol: '৳' },
  { name: 'SRI LANKAN RUPEE', value: 3.5, flag: '🇱🇰', symbol: 'Rs' },
  { name: 'NEPALESE RUPEE', value: 1.60, flag: '🇳🇵', symbol: '₨' },
  { name: 'ISRAELI SHEKEL', value: 0.042, flag: '🇮🇱', symbol: '₪' },
  { name: 'IRANIAN RIAL', value: 505, flag: '🇮🇷', symbol: '﷼' },
  { name: 'MOROCCAN DIRHAM', value: 0.12, flag: '🇲🇦', symbol: 'MAD' },
  { name: 'ETHIOPIAN BIRR', value: 1.7, flag: '🇪🇹', symbol: 'Br' },
];